version: '2'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  zookeeper2:
    image: wurstmeister/zookeeper
    ports:
      - "3181:2181"
  zookeeper3:
    image: wurstmeister/zookeeper
    ports:
      - "4181:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "32768:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181,172.17.0.1:3181,172.17.0.1:4181
      KAFKA_ADVERTISED_PORT: 32768
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "32769:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181,172.17.0.1:3181,172.17.0.1:4181
      KAFKA_ADVERTISED_PORT: 32769
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "32770:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181,172.17.0.1:3181,172.17.0.1:4181
      KAFKA_ADVERTISED_PORT: 32770
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
