version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "32768:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 32768
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: -1 # Retain all topics forever, hours
      KAFKA_LOG_RETENTION_BYTES: -1 # Retain all topics forever, bytes
      KAFKA_log_SEGMENT_BYTES: 134217728 # Here 8 times less for testing purposes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./brokers/broker1:/kafka:rw
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "32769:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 32769
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: -1 # Retain all topics forever, hours
      KAFKA_LOG_RETENTION_BYTES: -1 # Retain all topics forever, bytes
      KAFKA_log_SEGMENT_BYTES: 134217728 # Here 8 times less for testing purposes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./brokers/broker2:/kafka:rw
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "32770:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 32770
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: -1 # Retain all topics forever, hours
      KAFKA_LOG_RETENTION_BYTES: -1 # Retain all topics forever, bytes
      KAFKA_log_SEGMENT_BYTES: 134217728 # Here 8 times less for testing purposes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./brokers/broker3:/kafka:rw
